name: Publish to NPM

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          version: "latest"

      - name: Set up Node and NPM
        uses: actions/setup-node@v5

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Show Bun revision
        run: bun --revision

      - name: Show Bun uname
        run: uname -mprs

      - name: Validate package.json version matched tag
        run: |
          PACKAGE_VERSION=$(bun pm pkg get version | tr -d '"')
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          echo "Package version: $PACKAGE_VERSION"
          echo "Tag version: $TAG_VERSION"
          if [ "$PACKAGE_VERSION" != "$TAG_VERSION" ]; then
            echo "Version mismatch: package.json has $PACKAGE_VERSION but tag is $TAG_VERSION. Run 'bun bump' to increment version"
            exit 1
          fi
          echo "Version matches: $PACKAGE_VERSION"

      - name: Install dependencies
        run: bun install

      - name: Audit vulnerabilities
        run: bun audit

      - name: Use tsc to check for type safety
        run: bun lint

      - name: Run tests
        run: AGENT=1 bun test --bail=10

      - name: Build package
        run: bun run build

      - name: Publish to NPM
        run: npm publish


      